# Generated by Django 4.1.7 on 2023-04-02 14:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_author_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-createDate']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='createTime',
        ),
        migrations.AddField(
            model_name='post',
            name='createDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
